tecdoc_manufacturer_alias = {
  'FEBI': 'FEBI BILSTEIN',
  'ABS': 'A.B.S.',
  'HENGST': 'HENGST FILTER',
  'AMC FILTER': 'AMC Filter',
  'MAHLE': 'MAHLE ORIGINAL',
  'MANN': 'MANN-FILTER',
  'VICTOR REINZ': 'REINZ',
  'HERTH+BUSS': 'HERTH+BUSS JAKOPARTS',
  'KAVO': 'KAVO PARTS'
}